### ISSUE TITLE
fix: Investigate removing the dependency on pandas

### ISSUE THREAD

**Issue by carlosgjs** [noisepy/noisepy-io#6]
The only use of pandas in this package it to read a csv (in `channelcatalog.py1`). Instead, the built-in `csv` module could be used. E.g. https://medium.com/@AIWatson/how-to-read-csv-files-in-python-without-pandas-b693fc7ea3b7

**Comment by IshikaKhandelwal** [comment]
Pandas is required for the `stats2inv_mseed` function in the package. Therefore, we'll maintain pandas import for this purpose. Closing the issue.
